
name: Dataset Update

on:
  push:
    branches: 
    -  main 
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Generate Denmark data
      run: python scripts/Denmark-crawler.py
      continue-on-error: true

    - name: Generate Hungary data
      run: python scripts/Hungary-crawler.py
      continue-on-error: true

    - name: Generate Croatia data
      run: python scripts/Croatia-crawler.py
      continue-on-error: true

    - name: Generate Slovakia data
      run: python scripts/Slovakia-crawler.py
      continue-on-error: true

    - name: Generate Bulgaria data
      run: python scripts/Bulgaria-crawler.py
      continue-on-error: true

    - name: Generate India data
      run: python scripts/India-crawler.py
      continue-on-error: true

    - name: Generate Kazakhstan data
      run: python scripts/Kazakhstan-crawler.py
      continue-on-error: true

    - name: Generate NewZealand data
      run: python scripts/NewZealand-crawler.py
      continue-on-error: true

    - name: Generate Jamaica data
      run: python scripts/Jamaica-crawler.py
      continue-on-error: true

    - name: Generate Myanmar data
      run: python scripts/Myanmar-crawler.py
      continue-on-error: true

    - name: Generate Panama data
      run: python scripts/Panama-crawler.py
      continue-on-error: true

    - name: Generate Switzerland data
      run: python scripts/Switzerland-crawler.py
      continue-on-error: true

    - name: Generate Moldova data
      run: python scripts/Moldova-crawler.py
      continue-on-error: true

    - name: Generate Somalia data
      run: python scripts/Somalia-crawler.py
      continue-on-error: true

    - name: Generate Chile data
      run: python scripts/Chile-crawler.py
      continue-on-error: true

    - name: Generate Austria data
      run: python scripts/Austria-crawler.py
      continue-on-error: true

    - name: Generate BosniaHerzegovina data
      run: python scripts/BosniaHerzegovina-crawler.py
      continue-on-error: true

    - name: Generate Nigeria data
      run: python scripts/Nigeria-crawler.py
      continue-on-error: true


    - name: Generate Libya data
      run: python scripts/Libya-crawler.py
      continue-on-error: true


    - name: Generate Malaysia data
      run: python scripts/Malaysia-crawler.py
      continue-on-error: true


    - name: Generate Bangladesh data
      run: python scripts/Bangladesh-crawler.py
      continue-on-error: true


    - name: Generate Lebanon data
      run: python scripts/Lebanon-crawler.py
      continue-on-error: true

    - name: Generate ElSalvador data
      run: python scripts/ElSalvador-crawler.py
      continue-on-error: true


    - name: Generate Honduras data
      run: python scripts/Honduras-crawler.py
      continue-on-error: true

    - name: Generate Ghana data
      run: python scripts/Ghana-crawler.py
      continue-on-error: true

    - name: Generate Romania data
      run: python scripts/Romania-crawler.py
      continue-on-error: true

    - name: Generate Vietnam data
      run: python scripts/Vietnam-crawler.py
      continue-on-error: true


    - name: Generate Japan data
      run: python scripts/Japan-crawler.py
      continue-on-error: true


    - name: Generate Ukraine data
      run: python scripts/Ukraine-crawler.py
      continue-on-error: true

    - name: Generate Latvia data
      run: python scripts/Latvia-crawler.py
      continue-on-error: true

    - name: Generate Albania data
      run: python scripts/Albania-crawler.py
      continue-on-error: true


    - name: Generate Sweden data
      run: python scripts/Sweden-crawler.py
      continue-on-error: true


    - name: Generate Brazil data
      run: python scripts/Brazil-crawler.py
      continue-on-error: true

    - name: Generate Russia data
      run: python scripts/Russia-crawler.py
      continue-on-error: true

    - name: Commit data files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git status
        git add .
        git commit -m "Dataset Update" || echo "Nothing to commit"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: stccenter/COVID-19-Crawler-Data
        github_token: ${{ secrets.GITHUB_TOKEN }}
