name: Pdf dataset update
on:
  push:
    branches:
      - main
  schedule:name: Pdf dataset update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip install -r requirements.txt
        
        
      #Country 48
      - name: Generate Srilanka data
        run: python scripts/SriLanka-crawler.py
        continue-on-error: true

      #Country 49
      - name: Generate Slovenia data
        run: python scripts/Slovenia-crawler.py
        continue-on-error: true

      #Country 50
      - name: Generate Turkey data
        run: python scripts/Turkey-crawler.py
        continue-on-error: true
        
      - name: Commit data files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          git add .
          git commit -m "Dataset Update" || echo "Nothing to commit"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          repository: stccenter/COVID-19-Crawler-Data
          github_token: ${{ secrets.GITHUB_TOKEN }}
        
  